"""user

Revision ID: 2a78b95589b9
Revises: e4b0f057f2f8
Create Date: 2026-04-26 16:10:00.707389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a78b95589b9'
down_revision: Union[str, Sequence[str], None] = 'e4b0f057f2f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('response_time_ms', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('is_answered', sa.Boolean(), nullable=True))
    op.alter_column('messages', 'bot_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('verified_at', sa.DateTime(), nullable=True))
    op.add_column('widget_bots', sa.Column('docs_indexed', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('widget_bots', 'docs_indexed')
    op.drop_column('users', 'verified_at')
    op.drop_column('users', 'is_verified')
    op.alter_column('messages', 'bot_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('messages', 'is_answered')
    op.drop_column('messages', 'response_time_ms')
    # ### end Alembic commands ###
