"""add_bot_customization_fields

Revision ID: b5b58b9c7256
Revises: a12188c232f2
Create Date: 2026-05-02 14:01:01.414984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5b58b9c7256'
down_revision: Union[str, Sequence[str], None] = 'a12188c232f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verification_token_expires', sa.DateTime(), nullable=True))
    op.add_column('widget_bots', sa.Column('accent_color', sa.String(), nullable=True))
    op.add_column('widget_bots', sa.Column('welcome_message', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('widget_bots', 'welcome_message')
    op.drop_column('widget_bots', 'accent_color')
    op.drop_column('users', 'verification_token_expires')
    # ### end Alembic commands ###
