"""add admin fields

Revision ID: e4b0f057f2f8
Revises: 55c3bdb96ce8
Create Date: 2026-04-25 21:52:13.345954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e4b0f057f2f8'
down_revision: Union[str, Sequence[str], None] = '55c3bdb96ce8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE plantier AS ENUM ('free', 'starter', 'growth', 'enterprise');
        EXCEPTION WHEN duplicate_object THEN null;
        END $$;
    """)

    op.execute("""
        DO $$ BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_name='users' AND column_name='plan'
            ) THEN
                ALTER TABLE users ADD COLUMN plan plantier NOT NULL DEFAULT 'free';
            END IF;
        END $$;
    """)

    op.create_table('feedback',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('bot_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['widget_bots.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_bot_id'), 'feedback', ['bot_id'], unique=False)
    op.add_column('messages', sa.Column('bot_id', sa.String(), nullable=False))
    op.add_column('messages', sa.Column('success', sa.Boolean(), nullable=True))
    op.add_column('messages', sa.Column('response_ms', sa.Integer(), nullable=True))
    op.alter_column('messages', 'role',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('messages', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_index(op.f('ix_messages_bot_id'), 'messages', ['bot_id'], unique=False)
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_messages_session_id'), 'messages', ['session_id'], unique=False)
    op.drop_constraint(op.f('messages_session_id_fkey'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'widget_bots', ['bot_id'], ['id'])
    op.drop_column('messages', 'sources')
    op.add_column('users', sa.Column('mrr', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('renewal_date', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('messages_quota', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('messages_used', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('docs_quota', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('docs_indexed', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('storage_quota_gb', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('storage_used_gb', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('users', 'storage_used_gb')
    op.drop_column('users', 'storage_quota_gb')
    op.drop_column('users', 'docs_indexed')
    op.drop_column('users', 'docs_quota')
    op.drop_column('users', 'messages_used')
    op.drop_column('users', 'messages_quota')
    op.drop_column('users', 'renewal_date')
    op.drop_column('users', 'mrr')
    op.execute("ALTER TABLE users DROP COLUMN IF EXISTS plan")
    op.execute("DROP TYPE IF EXISTS plantier")
    op.add_column('messages', sa.Column('sources', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_session_id_fkey'), 'messages', 'chat_sessions', ['session_id'], ['id'])
    op.drop_index(op.f('ix_messages_session_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_bot_id'), table_name='messages')
    op.alter_column('messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('messages', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('messages', 'role',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('messages', 'response_ms')
    op.drop_column('messages', 'success')
    op.drop_column('messages', 'bot_id')
    op.drop_index(op.f('ix_feedback_bot_id'), table_name='feedback')
    op.drop_table('feedback')
    # ### end Alembic commands ###